import CrudPage from '../components/CrudPage'
import { AccessDenied } from '../components/RoleGuard'
import { useAuth } from '../context/AuthContext'

const fields = [
  { name: 'reportCode', label: 'Report Code', type: 'text', required: true },
  { name: 'reportName', label: 'Report Name', type: 'text', required: true },
  {
    name: 'reportType',
    label: 'Report Type',
    type: 'select',
    options: ['BarangaySummary', 'MonthlyCollection', 'AnnualSummary', 'DelinquencyList'],
    required: true,
  },
  { name: 'periodStart', label: 'Period Start', type: 'date', required: true },
  { name: 'periodEnd', label: 'Period End', type: 'date', required: true },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    options: ['Draft', 'ForReview', 'Approved', 'Published'],
    required: true,
  },
  { name: 'totalProperties', label: 'Total Properties', type: 'int', required: true },
  { name: 'totalAssessedValue', label: 'Total Assessed Value', type: 'number', required: true },
  { name: 'totalTaxDue', label: 'Total Tax Due', type: 'number', required: true },
  { name: 'totalCollected', label: 'Total Collected', type: 'number', required: true },
  { name: 'filePath', label: 'File Path', type: 'text' },
  { name: 'generatedBy', label: 'Generated By', type: 'int', required: true },
  { name: 'approvedBy', label: 'Approved By', type: 'int' },
  { name: 'generatedAt', label: 'Generated At', type: 'datetime-local' },
  { name: 'updatedAt', label: 'Updated At', type: 'datetime-local', inForm: false },
]

export default function ReportRecordsPage() {
  const { can, user } = useAuth()

  if (!can('reporting.view')) {
    return <AccessDenied requiredRole="Admin, Accountant, or Auditor" />
  }

  return (
    <CrudPage
      title="Report Records"
      endpoint="/ReportRecords"
      idField="reportRecordId"
      fields={fields}
      canCreate={can('reporting.generate')}
      canEdit={can('reporting.generate') || can('reporting.submit')}
      canDelete={user?.role === 'Admin'}
      readOnlyMessage="Read-only access. Report metadata is persisted in the report_records table."
    />
  )
}