import { useEffect, useMemo, useState } from 'react'
import api from '../../api'
import { AccessDenied, ReadOnlyBanner } from '../../components/RoleGuard'
import { useAuth } from '../../context/AuthContext'

const formatDateTime = (value) => {
  if (!value) return 'Unknown time'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString()
}

export default function AuditDataPage() {
  const { can, user } = useAuth()
  const [logs, setLogs] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [search, setSearch] = useState('')
  const [severity, setSeverity] = useState('All')
  const [moduleFilter, setModuleFilter] = useState('All')

  if (!can('audit.view')) {
    return <AccessDenied requiredRole="Admin or Auditor" />
  }

  const loadLogs = async () => {
    setLoading(true)
    setError('')

    try {
      const response = await api.get('/ActivityLogs')
      setLogs(Array.isArray(response.data) ? response.data : [])
    } catch (err) {
      setError(err?.message || 'Failed to load audit logs')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadLogs()
  }, [])

  const modules = useMemo(() => {
    return ['All', ...new Set(logs.map((item) => item.module).filter(Boolean))]
  }, [logs])

  const filteredLogs = useMemo(() => {
    const needle = search.trim().toLowerCase()
    return logs.filter((item) => {
      const matchesSearch = !needle || [item.action, item.module, item.description]
        .filter(Boolean)
        .some((value) => String(value).toLowerCase().includes(needle))
      const matchesSeverity = severity === 'All' || item.severity === severity
      const matchesModule = moduleFilter === 'All' || item.module === moduleFilter
      return matchesSearch && matchesSeverity && matchesModule
    })
  }, [logs, moduleFilter, search, severity])

  const counts = useMemo(() => {
    return {
      total: logs.length,
      info: logs.filter((item) => item.severity === 'Info').length,
      warning: logs.filter((item) => item.severity === 'Warning').length,
      critical: logs.filter((item) => item.severity === 'Critical').length,
    }
  }, [logs])

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-slate-900 tracking-tight">Audit Support</h1>
          <p className="text-sm text-slate-500 mt-1">System-generated audit trail backed by the activity_logs table.</p>
        </div>
        <button type="button" onClick={loadLogs} disabled={loading} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">
          {loading ? 'Refreshing...' : 'Refresh Logs'}
        </button>
      </div>

      <ReadOnlyBanner message={`Audit trail is read-only for ${user?.role}. Entries here are generated by actual database operations.`} />

      {error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {[
          { label: 'Total Logs', value: counts.total },
          { label: 'Info', value: counts.info },
          { label: 'Warning', value: counts.warning },
          { label: 'Critical', value: counts.critical },
        ].map((card) => (
          <div key={card.label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
            <p className="text-xs uppercase tracking-wider text-slate-500">{card.label}</p>
            <p className="mt-2 text-3xl font-semibold text-slate-900">{card.value}</p>
          </div>
        ))}
      </div>

      <div className="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div className="border-b border-slate-200 bg-slate-50/70 px-4 py-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex flex-col gap-3 sm:flex-row">
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search action, module, description..."
              className="rounded-lg border border-slate-200 px-3 py-2 text-sm"
            />
            <select value={severity} onChange={(event) => setSeverity(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">
              <option value="All">All Severities</option>
              <option value="Info">Info</option>
              <option value="Warning">Warning</option>
              <option value="Critical">Critical</option>
            </select>
            <select value={moduleFilter} onChange={(event) => setModuleFilter(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm">
              {modules.map((module) => (
                <option key={module} value={module}>{module}</option>
              ))}
            </select>
          </div>
          <span className="text-xs text-slate-500">{filteredLogs.length} matching log entries</span>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className="bg-slate-50 text-slate-500">
              <tr>
                <th className="px-4 py-3">Action</th>
                <th className="px-4 py-3">Module</th>
                <th className="px-4 py-3">Severity</th>
                <th className="px-4 py-3">Description</th>
                <th className="px-4 py-3">Created</th>
              </tr>
            </thead>
            <tbody>
              {filteredLogs.map((item) => (
                <tr key={item.logId} className="border-t border-slate-100">
                  <td className="px-4 py-3 font-medium text-slate-900">{item.action}</td>
                  <td className="px-4 py-3 text-slate-600">{item.module}</td>
                  <td className="px-4 py-3 text-slate-600">{item.severity}</td>
                  <td className="px-4 py-3 text-slate-600">{item.description || 'No description'}</td>
                  <td className="px-4 py-3 text-slate-600">{formatDateTime(item.createdAt)}</td>
                </tr>
              ))}
              {filteredLogs.length === 0 && !loading && (
                <tr>
                  <td colSpan={5} className="px-4 py-8 text-center text-sm text-slate-500">No audit logs found.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}